services:
  db:
    container_name: kiln-db-dev
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=postgres
    image: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./data/db:/var/lib/postgres/data
version: "3.8"
