linters:
  enable-all: true

  # enable:
  #   - stylecheck
  #   - testifylint

  disable:
    # deprecated linters
    - maligned
    - deadcode
    - structcheck
    - interfacer
    - ifshort
    - exhaustivestruct
    - nosnakecase
    - golint
    - varcheck
    - scopelint

    - errcheck

    # too much noise
    - tagalign
