definitions:
  dto.DataDelegationSliceResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/dto.DelegationResponse'
        type: array
    type: object
  dto.DelegationResponse:
    properties:
      amount:
        type: string
      block:
        type: string
      delegator:
        type: string
      timestamp:
        type: string
    type: object
  errorhandling.SimpleErrorMessage:
    properties:
      error:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Check the status of the REST API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check Status
      tags:
      - health
  /xtz/delegations:
    get:
      consumes:
      - application/json
      description: List all the aggregated new delegations
      parameters:
      - description: Filter results by year
        in: query
        name: year
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.DataDelegationSliceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorhandling.SimpleErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorhandling.SimpleErrorMessage'
      summary: List Delegations
      tags:
      - delegations
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
